coffee_shop:
  outputs:
    dev:
      type: bigquery
      threads: 8
      method: oauth
      project: demo_dbt_project # update this to be the name of your project
      dataset: dbt_marc # update this to be your name
      threads: 8
      timeout_seconds: 300
      location: US
      priority: interactive
      retries: 1
  target: dev